{{- if and (eq .Values.armAuth.type "servicePrincipal") .Values.armAuth.secretJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: ingress-azure-identity
  namespace: kube-system
type: Opaque
data:
  servicePrincipal.json: {{ .Values.armAuth.secretJSON | b64enc | quote }}
{{- end }}
